<?php // $Id: order.module, v 1.0 2011/07/02 12:37:27 ITKLD Exp $
/**
 * Copyright 2011-2017 Itinity Ltd. (itinity.ru). All rights reserved.
 * Licensed under the GNU General Public License, version 2 or later.
 */

define('ORDER_DEBUG', 0);


/**
 * Definition of order statuses.
 */
define('ORDER_STATUS_DELIVERY_ISSUED', 0);
define('ORDER_STATUS_DELIVERY_PREPARED', 0x0001);
define('ORDER_STATUS_DELIVERED', 0x0004);

define('ORDER_ANNONYMOUS_ACCESS_TIMEOUT', 3600 * 24 * 7);

require_once dirname(__FILE__) . '/order.form.inc';
require_once dirname(__FILE__) . '/order.mail.inc';


/**
 * Implements hook_menu().
 */
function order_menu() {
  $items['shop/cart'] = array(
    'title' => 'Shopping cart',
    'page callback' => 'order_shop_cart_page',
    'page arguments' => array(NULL, 2,), // optional shop_id
    'access arguments' => array('access content',),
    'type' => MENU_CALLBACK,
  );
  $items['shop/order'] = $items['shop/cart']; // Legacy menu item duplicate. Keep it for SEO (e.g. existing settings in google analytics)

  $items['shop/cart/%/order'] = array(
    'title' => 'Checkout order',
    'page callback' => 'order_shop_cart_checkout_page',
    'page arguments' => array(NULL, 2,), // shop_id required
    'access arguments' => array('access content',),
    'type' => MENU_CALLBACK,
  );


  $items['user/%user/shop'] = array(
    'title' => 'Purchases and payments',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shop_orders_form', 1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1, ),
//    'access arguments' => array('edit own order content'),
    'file' => 'order.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/shop/orders'] = array(
    'title' => 'Orders',
    'access callback' => 'user_edit_access',
    'access arguments' => array(1, ),
//    'access arguments' => array('edit own order content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['user/%user/shop/processed'] = array( // arg(3) == processed, @see shop_orders_form()
    'title' => 'Processed',
    'title callback' => '_admin_shop_orders_processed_title_callback',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shop_orders_form', 1),
    'access arguments' => array('edit own order content'),
    'file' => 'order.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => -9,
  );

  $items['user/%user/shop/cart'] = array(
    'title' => 'Shopping cart',
    'page callback' => 'order_shop_cart_page',
    'page arguments' => array(1, 4,), // 4 - optional shop_id
    'access callback' => 'user_edit_access',
    'access arguments' => array(1,),
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/shop/cart/%/order'] = array(
    'title' => 'Checkout order',
    'page callback' => 'order_shop_cart_checkout_page',
    'page arguments' => array(1, 4,),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1, 4,), // shop_id required
    'type' => MENU_CALLBACK,
  );

  $items['admin/shop/orders'] = array(
    'title' => 'Orders',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shop_orders_form'),
    'access arguments' => array('bypass node access'),
    'file' => 'order.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/shop/orders/list'] = array(
    'title' => 'Order list',
    'access arguments' => array('bypass node access'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  if (module_invoke('status', 'get_settings', 'node', 'order')) {
    $items['admin/shop/orders/list']['title'] = 'In work';

    $items['admin/shop/orders/processed'] = array(
      'title callback' => '_admin_shop_orders_processed_title_callback',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shop_orders_form'),
      'access arguments' => array('bypass node access'),
      'file' => 'order.admin.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => -9,
    );

    /*
		$items['admin/shop/orders/closed'] = array(
			'title' => 'Finished',
			'page callback' => 'drupal_get_form',
			'page arguments'	=> array('shop_orders_form'),
			'access arguments'	=> array('bypass node access'),
			'file' => 'order.admin.inc',
			'type' => MENU_LOCAL_TASK,
      'weight' => -9,
		);
    $items['admin/shop/orders/cancelled'] = array(
      'title' => 'Cancelled',
      'page callback' => 'drupal_get_form',
      'page arguments'	=> array('shop_orders_form'),
      'access arguments'	=> array('bypass node access'),
      'file' => 'order.admin.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => -8,
    );
    */

    $items['admin/shop/orders/statistics'] = array(
      'title' => 'Statistics',
      'page callback' => array('orders_statistics_page'),
      'access arguments' => array('bypass node access'),
      'weight' => -7,
      'type' => MENU_LOCAL_TASK,
      'file' => 'order.admin.inc',
    );

//		$items['admin/shop/orders/graph'] = array(
//			'title' => 'Graph',
//			'page callback' => 'drupal_get_form',
//			'page arguments' => array('orders_graph_form'),
//			'access arguments'	=> array('bypass node access'),
//			'file' => 'order.admin.inc',
//			'type' => MENU_LOCAL_TASK,
//			'weight' => 9,
//		);

    // @todo delete
//		$items['admin/shop/orders/by_status'] = array(
//			'title' => 'By status',
//			'page callback' => 'orders_by_status_page',
//			'access arguments'	=> array('bypass node access'),
//			'file' => 'order.admin.inc',
//			'type' => MENU_LOCAL_TASK,
//			'weight' => 10,
//		);
  }

  $items['admin/config/shop/messages'] = array(
    'title' => 'Messages',
    'page arguments' => array('order_setting_recipients_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'order.mail.inc',
    'weight' => 5,
  );

  if (!module_invoke('status', 'get_settings', 'node', 'order')) { // @see status.module
    $items['node/%node/order_status'] = array(
      'title' => 'Status',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_order_status_change_form', 1),
      'access arguments' => array('administer moneys'),
    );
  }

  $anonymous_perms = user_role_permissions(array(DRUPAL_ANONYMOUS_RID => user_role_load(DRUPAL_ANONYMOUS_RID)));
  $anonymous_perms = reset($anonymous_perms);
  if (!empty($anonymous_perms['submit orders'])) {
    $items['shop/anonymous-auth/%order_by_number/%/%'] = array(
      'title' => 'Temporary grant access to orders for anonymous users',
      'page callback' => 'order_anonymous_auth',
      'page arguments' => array(2, 3, 4),
      'access callback' => 'user_is_anonymous',
      'type' => MENU_CALLBACK,
    );
  }
  return $items;
}


function _admin_shop_orders_processed_title_callback() {
  return t('Processed', array(), array('context' => 'plural'));
}


/**
 * Helper function.
 * Generate order access key for anonymous users. @see order_request_token_form() and order_anonymous_auth()
 */
function _order_private_token($order_node, $timestamp = NULL) {
  return drupal_hmac_base64(($timestamp ? $timestamp : REQUEST_TIME) . ':' . $order_node->nid, drupal_get_hash_salt() . drupal_get_private_key());
}


/**
 * Page callback for /shop/anonymous-auth/%order_by_number/%/%
 * Grant temporary order view access using private url and redirect to node/nid
 */
function order_anonymous_auth($order_node, $token, $timestamp) {
  if ($token && $timestamp && user_access('submit orders') && REQUEST_TIME - $timestamp <= ORDER_ANNONYMOUS_ACCESS_TIMEOUT) {
    if (_order_private_token($order_node, $timestamp) === $token) {
      if (!isset($_COOKIE['order-auth'][$order_node->nid]['timestamp']) || $_COOKIE['order-auth'][$order_node->nid]['timestamp'] < $timestamp) {
        order_grant_temporary_access($order_node, $timestamp);
      }
    }
  }
  $uri = entity_uri('node', $order_node);
  if ($_GET['q'] !== $uri['path']) {
    drupal_goto($uri['path']);
  }
}


/**
 * Grant temporary order view access using cookies for anonymous user @see _order_node_form_submit()
 */
function order_grant_temporary_access($order_node, $timestamp = NULL, $set_message = TRUE) {
  if ($new_token = _order_private_token($order_node, REQUEST_TIME)) {
    $timestamp = $timestamp ? $timestamp : REQUEST_TIME;
    if (!isset($_COOKIE['order-auth'][$order_node->nid]['token']) || $_COOKIE['order-auth'][$order_node->nid]['token'] !== $new_token) {

      $node_access_rights = &drupal_static('node_access', array());
      unset($node_access_rights[$GLOBALS['user']->uid][$order_node->nid]);

      $_COOKIE['order-auth'][$order_node->nid]['token'] = $new_token;
      setrawcookie('order-auth[' . $order_node->nid . '][token]', rawurlencode($_COOKIE['order-auth'][$order_node->nid]['token']), $timestamp + ORDER_ANNONYMOUS_ACCESS_TIMEOUT, '/');
      $_COOKIE['order-auth'][$order_node->nid]['timestamp'] = REQUEST_TIME;
      setrawcookie('order-auth[' . $order_node->nid . '][timestamp]', REQUEST_TIME, $timestamp + ORDER_ANNONYMOUS_ACCESS_TIMEOUT, '/');
      if ($set_message) {
        drupal_set_message(rtrim(t('Store opened you temporary access to the order #@num. Duration access is @timeout.', array('@num' => $order_node->order_num, '@timeout' => format_interval(ORDER_ANNONYMOUS_ACCESS_TIMEOUT - (REQUEST_TIME - $timestamp)))), '.') . '.');
      }
      return TRUE;
    }
  }
}

/**
 * Form callback.
 * Request temporary access to order for anonymous user
 */
function order_request_token_form($form, &$form_state, $order_node = NULL) {
  return array(
    '#spam_protect' => TRUE,  // @see _spam_protect_form_needs_protection()
    '#attributes' => array(
      'class' => array('container-inline',),
    ),
    'order_num' => array(
      '#type' => 'textfield',
      '#title' => t('Order number'),
      '#required' => TRUE,
      '#default_value' => $order_node ? $order_node->order_num : NULL,
      '#size' => 10,
    ),
    'actions' => array(
      '#type' => 'actions',
      'request' => array(
        '#type' => 'submit',
        '#value' => t('Get temporary access via e-mail'),
      ),
    ),
  );

}


/**
 * Validate order_request_token_form
 */
function order_request_token_form_validate($form, &$form_state) {
  if (user_is_logged_in()) {
    form_error($form['actions']['request'], t('You already logged in'));
  }
  else {
    if ($order_node = order_by_number_load($form_state['values']['order_num'])) {
      // IKW: DONT WANT IT:
      // Do not allow request orders with registered owners or orders without recipient email.
      /*if ($order_node->uid && user_load($order_node->uid)) {
        form_error($form['order_num'], t('This order is attached to registered account. If you are is owner of this order, please go to !log-in-link', array('!log-in-link' => l(t('Log in'), 'user', array(
          'query' => drupal_get_destination(),
          'attributes' => array('class' => array('form-submit',)),
        )))));
      }
      else*/
      if (empty($order_node->recipient_fields['mail'])) {
        form_error($form['order_num'], t('Order #@num not contains information about recipient email address.', array('@num' => $order_node->order_num)));
      }
      // Flood protection (5 requests per hour)
      elseif (!flood_is_allowed('order_view_request', 5, 3600)) {
        form_error($form['actions']['request'], t('You cannot submit request more than %limit orders in @interval. Try again later.', array('%limit' => 5, '@interval' => format_interval(3600))));
      }
    }
    else {
      form_error($form['order_num'], t('Order #@num not found', array('@num' => $form_state['values']['order_num'],)));
    }
  }
}


/**
 * Submit callback for order_request_token_form
 * Send temporary private access link to anonymous owner of order node.
 */
function order_request_token_form_submit($form, &$form_state) {
  if (($order_node = order_by_number_load($form_state['values']['order_num'])) && !empty($order_node->recipient_fields['mail'])) {
    flood_register_event('order_view_request', 3600);
    drupal_mail('order', 'request_anonymous_link', $order_node->recipient_fields['mail'], $GLOBALS['language'], array(
      'order' => $order_node,
      'url' => url('shop/anonymous-auth/' . $order_node->order_num . '/' . _order_private_token($order_node) . '/' . REQUEST_TIME, array('absolute' => TRUE, 'alias' => TRUE,)),
    ));
    drupal_set_message(t('Message with instructions for access to order #@num was sent to your e-mail address.', array('@num' => $order_node->order_num,)));
    $_GET['destination'] = '';
  }
}


/**
 * Implements hook_block_view_alter()
 */
function order_block_view_alter(&$data, $block) {
  // Inject request temporary access form for order into main content Only for anonymous users on forbidden "node/123" order view pages
  if ($block->module === 'system' && $block->delta === 'main') {
    if (!user_is_logged_in()) {
      $menu_item = menu_get_item();
      if (isset($menu_item['access']) && !$menu_item['access'] && $menu_item['path'] === 'node/%') {
        if (($nid = preg_replace('/^node\/(\d+)$/', '$1', $menu_item['href'])) && user_access('submit orders') && ($node = node_load($nid)) && $node->type === 'order') {
          $data['content']['order_request_token_form'] = drupal_get_form('order_request_token_form', $node);
        }
      }
    }
  }
}


/**
 * Implements hook_menu_alter().
 */
function order_menu_alter(&$items) {
  $items['node/add/order']['access callback'] = '_order_node_add_access';
  unset($items['user/%user/content/order']); // @see social_profile.module
}


/**
 * Access callback for /node/add/order @see order_menu_alter()
 */
function _order_node_add_access() {
  return user_access('administer moneys');// || node_access('create', 'order');
}


/**
 * Implements hook_admin_menu_output_alter()
 */
function order_admin_menu_output_alter(&$content) {
  if (!user_access('administer moneys')) {
    unset($content['menu']['node/add']['node/add/order']);
  }
}


/**
 * Implements hook_theme()
 */
function order_theme($existing, $type, $theme, $path) {
  return array(
    'shop_cart_form' => array(
      'render element' => 'shop_cart_form',
      'file' => 'order.theme.inc',
    ),
    'shop_orders_form' => array(
      'render element' => 'form',
      'file' => 'order.admin.inc',
    ),
  );
}


/**
 * Implements hook_shop_settings_alter()
 * Suppress order type in sellable node types in admin setup
 */
function order_shop_get_info_alter(&$info) {
  unset($info['entity_types']['node']['order']);
}


/**
 * Implements hook_seo_entity_supported()
 */
function order_seo_entity_supported($entity_type, $entity = NULL, $bundle = NULL, $bundle_info = NULL) {
  if ($entity_type === 'node' && ((isset($entity->type) && $entity->type === 'order') || ($bundle === 'order'))) {
    return FALSE;
  }
}


/**
 * Callback for /shop/cart[/%]
 * Shopping cart pages.
 */
function order_shop_cart_page($account = NULL, $shop_id = NULL) {
  if (arg(0) . '/' . arg(1) === 'shop/order') { // google analytics legacy @see also order_menu()
    $get = $_GET;
    unset($get['q']);
    unset($_GET['destination']); // fix problem where drupal_goto() ignores passed url and get to 'destination' param if exists
    drupal_goto('shop/cart' . (isset($shop_id) ? '/' . $shop_id : ''), array('query' => $get), 301); // "document moved permanently"
  }

  $build = array();
  foreach (shop_cart_multiple($account, $shop_id) as $sid => $shop_cart) {
    if (!$shop_cart->is_empty()) {
      $build[$sid]['form'] = drupal_get_form('order_shop_cart_form', $shop_cart);
    }
  }
  if (count($build) > 1 && !isset($build[$sid]['form']['shop_cart']['shop_name']['#access'])) {
    $build[$sid]['form']['shop_cart']['shop_name']['#access'] = TRUE;
  }
  if (!$build) {
    $build[]['#markup'] = t('Cart is empty');
  }
  return $build;
}


/**
 * Implements hook_query_TAG_alter()
 */
function order_query_entity_selector_alter(QueryAlterableInterface $query) {
  if ($params = $query->getMetaData('selector_params')) {
    if (isset($params['shop_cart_shop_id'])) { // @see order_shop_cart_form()
      $query->innerJoin('shop_index', 'si', 'si.entity_type = :t AND si.entity_id = base.nid', array(':t' => $params['entity_type'])); // TODO: get 'nid' column name using entity API
      $query->condition('si.shop_id', $params['shop_cart_shop_id']);
    }
  }
}

/**
 * Page callback for /shop/cart/%/order and /user/%user/shop/cart/%/order
 */
function order_shop_cart_checkout_page($account = NULL, $shop_id = NULL) {
  if (!isset($shop_id) || !shop_list_shops($shop_id)) {
    drupal_not_found();
    drupal_exit();
  }
  if (shop_cart($shop_id, $account)->is_empty(FALSE)) {
    unset($_GET['destination']);
    drupal_goto('shop/cart/' . $shop_id);
  }

  module_load_include('inc', 'node', 'node.pages');
  // Modified node_add():
  $account = $account ? $account : $GLOBALS['user'];
  $types = node_type_get_types();
  $node = (object) array('uid' => $account->uid, 'name' => (isset($account->name) ? $account->name : ''), 'type' => 'order', 'language' => LANGUAGE_NONE);
  drupal_set_title(t('Create @name', array('@name' => $types['order']->name)), PASS_THROUGH);
  $node->shop_id = $shop_id;
  return drupal_get_form('order_node_form', $node); // @see order_form()

  // old: 
  // old: module_load_include('inc', 'node', 'node.pages');
  // old: return node_add('order');
}

/**
 * Implements hook_node_info().
 */
function order_node_info() {
  $t = get_t();
  return array(
    'order' => array(
      'name' => $t('Order'),
      'base' => 'order',
      'description' => $t('Order content type for shop orders.'),
      'has_title' => FALSE,
      'modified' => FALSE,
      'custom' => FALSE,
      'type' => 'order',
      'locked' => TRUE,
    ),
  );
}

/**
 * Implements hook_node_access
 */
function order_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;
  global $user;

  if ($type === 'order') {
    if ($op === 'view') {
      $customer = shop_get_customer($node);

      $access = (user_access('edit any order content', $account) || ($account->uid && $node->uid == $account->uid)
        || ($customer->uid && $customer->uid == $account->uid)) ? NODE_ACCESS_ALLOW : NODE_ACCESS_DENY;

//			 bad gateway error on production server
//				if ($access === NODE_ACCESS_DENY && node_is_page($node)) {
//				 @TODO: validate href token and grant access (like user password reset)
//			}

      // Grant view access by cookies for anonymous users
      if ($access === NODE_ACCESS_DENY && !$user->uid && !$account->uid) {
        if (
          node_access('create', 'order')
          &&
          !empty($_COOKIE['order-auth'][$node->nid]['token'])
          && !empty($_COOKIE['order-auth'][$node->nid]['timestamp'])
          && REQUEST_TIME - ORDER_ANNONYMOUS_ACCESS_TIMEOUT < $_COOKIE['order-auth'][$node->nid]['timestamp']
          && $_COOKIE['order-auth'][$node->nid]['token'] === _order_private_token($node, $_COOKIE['order-auth'][$node->nid]['timestamp'])
        ) {
          $access = NODE_ACCESS_ALLOW;
        }
      }

      return $access;
    }
    if ($op === 'create') {
      return user_access('submit orders', $account) || user_access('administer moneys', $account) ? NODE_ACCESS_ALLOW : NODE_ACCESS_DENY;
    }
    if ($op === 'update') {
      if (user_access('edit any order content', $account) ||
        ($account->uid && $account->uid == $node->uid && user_access('edit own order content', $account) && $node->status && !$node->is_complete && !$node->is_paid)
      ) {
        return NODE_ACCESS_ALLOW;
      }
      else {
        return NODE_ACCESS_DENY;
      }
    }

    if ($op === 'delete') {
      if (user_access('edit any order content', $account) ||
        ($account->uid && $account->uid == $node->uid && user_access('delete own order content', $account) && $node->status && !$node->is_complete)
      ) {
        return NODE_ACCESS_ALLOW;
      }
      else {
        return NODE_ACCESS_DENY;
      }
    }
    return NODE_ACCESS_DENY;
  }
  return NODE_ACCESS_IGNORE;
}


/**
 * Callback for /node/%node/order_status
 */

function _order_status_change_form($form, &$form_state, $node) {
  $form['status'] = array(
    '#type' => 'checkbox',
    '#title' => t('Accepted'),
    '#default_value' => $node->status,
  );
  $form['order_status'] = array(
    '#type' => 'select',
    '#title' => t('Order current status'),
    '#options' => _order_statuses(),
    '#default_value' => !empty($node->order_status) ? $node->order_status : array(),
  );
  $form['#node'] = $node;
  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Apply'),
    ),
  );
  return $form;
}


function _order_status_change_form_submit($form, &$form_state) {
  if ($node = node_load($form['#node']->nid)) {
    $need_update = FALSE;
    if ((bool) $node->status !== (bool) $form_state['values']['status']) {
      $node->status = $form_state['values']['status'];
      $need_update = TRUE;
    }
    if (array_sum($node->order_status) != $form_state['values']['order_status']) {
      $node->order_status = $form_state['values']['order_status'];
      $need_update = TRUE;
      if (module_exists('changelog')) {
        $options = _order_statuses();
        changelog_add($node, 'node', 'order', 'Status changed to <b>@status</b>', array('@status' => $options[$form_state['values']['order_status']]));
      }
    }
    if ($need_update) {
      node_save($node);
    }
  }
}


/**
 * Helper function - return array for #options key in select.
 */
function _order_statuses() {
  return array(
    ORDER_STATUS_DELIVERY_ISSUED => t('Issued'),
    ORDER_STATUS_DELIVERY_PREPARED => t('Prepared to delivery'),
    ORDER_STATUS_DELIVERED => t('Delivered'),
  );
}

/**
 * Implements hook_module_implements_alter()
 */
function order_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'form_alter') {
    // Put order_form_alter() into the end of hooks queue.
    $bool = $implementations['order'];
    unset($implementations['order']);
    $implementations['order'] = $bool;
  }
  if ($hook === 'node_load') {
    // Put order_node_load() into the end of hooks queue.
    $bool = $implementations['order'];
    unset($implementations['order']);
    $implementations['order'] = $bool;
  }
}


function order_entity_load($entities, $entity_type) {
  if ($entity_type === 'node') {
    $orders = array();
    foreach ($entities as $n) {
      if ($n->type === 'order') {
        $orders[$n->nid] = $n;
      }
    }

    if ($orders) {
      foreach (db_query('SELECT * FROM {shop_orders} so WHERE so.nid IN(:nids)', array(':nids' => array_keys($orders))) as $result) {
        $nid = $result->nid;
        foreach ($result as $key => $val) {
          $orders[$nid]->{$key} = $val;
        }
        _order_extract_status($orders[$nid]);
        $orders[$nid]->delivery_params = $result->delivery_params ? unserialize($result->delivery_params) : NULL;
        $orders[$nid]->previous_state = $result->previous_state ? unserialize($result->previous_state) : NULL;
        unset($orders[$nid]->previous_state->previous_state);
        $orders[$nid]->recipient_fields = $result->recipient_fields ? unserialize($result->recipient_fields) : array();

        $orders[$nid]->shop_id = $result->shop_id;
      }
    }    
  }
}


/**
 * Implements hook_node_load().
 */
function order_node_load($nodes, $types) {
  foreach ($nodes as $n) {
    if ($n->type === 'order') {
      $n->is_complete = order_is_complete($n);
      $n->frozen = order_is_frozen($n);      
    }
  }
}

/**
 * Load order node by order_num field
 */
function order_by_number_load($order_num) {
  if ($nid = db_query('SELECT nid FROM {shop_orders} WHERE order_num = :n', array(':n' => $order_num))->fetchField()) {
    return node_load($nid);
  }
}

/**
 * Implements hook_prepare().
 */
function order_prepare($node) {
  $node->language = LANGUAGE_NONE;
  if (empty($node->nid)) {
    $node->is_paid = FALSE;
    $node->is_complete = FALSE;
    $node->frozen = FALSE;
    $node->shop_id = isset($node->shop_id) ? $node->shop_id : 0;
    if (!isset($node->user_ip)) {
      $node->user_ip = ip_address();
    }
  }
}


/**
 * Implements hook_field_extra_fields().
 */
function order_field_extra_fields() {
  $extra['node']['order'] = array(
    'form' => array(
      'order_content' => array(
        'label' => t('Content of order'),
        'description' => t('Content of shop cart and delivery method'),
        'weight' => 0.0001,
      ),
      'order_discount' => array(
        'label' => t('Order discount'),
        'description' => t('Order discount'),
        'weight' => 0.0002,
      ),
      'customer' => array(
        'label' => t('Customer'),
        'description' => t('Customer'),
        'weight' => 0.0003,
      ),
      'order_information' => array(
        'label' => t('Recipient data'),
        'description' => t('Recipient data'),
        'weight' => 0.0004,
      ),
    ),
    'display' => array(
      'order_content' => array(
        'label' => t('Content of order'),
        'description' => t('Content of order'),
        'weight' => -10,
      ),
      'delivery' => array(
        'label' => t('Delivery information'),
        'label_display' => 'above',
        'description' => t('Delivery information'),
        'weight' => -9.99,
      ),
      'recipient' => array(
        'label' => t('Recipient data'),
        'label_display' => 'hidden',
        'description' => t('Information about recipient'),
        'weight' => 10,
      ),
      'customer' => array(
        'label' => t('Customer'),
        'label_display' => 'inline',
        'description' => t('Customer'),
        'weight' => 10,
      ),
      // ? 'invoice' => array(
      // ? 	'label' => t('Invoice'),
      // ? 	'description' => t('Invoice for payment'),
      // ? 	'weight' => 19,
      // ? ),
      'payment_widget' => array(
        'label' => t('Payment for order'),
        'description' => t('Payment for order'),
        'label_display' => 'hidden',
        'weight' => 20,
      ),
      'payment_status' => array(
        'label' => t('Payment status'),
        'description' => t('Payment status'),
        'label_display' => 'inline',
        'weight' => 20.000001,
      ),
    ),
  );
  if (!module_invoke('status', 'get_settings', 'node', 'order')) { // @see status.module
    $extra['node']['order']['display']['status_field'] = array(
      'label' => t('Order status'),
      'label_display' => 'inline',
      'description' => t('Current status of order'),
      'weight' => 10,
    );
  }
  return $extra;
}


/**
 * Implements hook_extra_field_widget_settings_form()
 * @see addons.module -->> _addons_extra_field_widget_settings_form()
 */
function order_extra_field_widget_settings_form($entity_type, $bundle, $field_name, $settings) {
  if ($entity_type === 'node' && $bundle === 'order' && $field_name === 'order_information') {
    return array(
      'enabled' => array(
        '#type' => 'container',
        '#tree' => TRUE,
        'title' => array('#type' => 'item', '#markup' => t('Enabled fields')),
        'lfm' => array(
          '#type' => 'checkbox',
          '#title' => t('L.F.M.'),
          '#default_value' => $settings['enabled']['lfm'] ?? TRUE,
        ),
        'phone' => array(
          '#type' => 'checkbox',
          '#title' => t('Phone'),
          '#default_value' => $settings['enabled']['phone'] ?? TRUE,
        ),
        'mail' => array(
          '#type' => 'checkbox',
          '#title' => t('E-mail'),
          '#default_value' => $settings['enabled']['mail'] ?? TRUE,
        ),
      ),
      'required' => array(
        '#type' => 'container',
        '#tree' => TRUE,
        'title' => array('#type' => 'item', '#markup' => t('Required fields')),
        'lfm' => array(
          '#type' => 'checkbox',
          '#title' => t('L.F.M.'),
          '#default_value' => $settings['required']['lfm'] ?? FALSE,
          '#states' => array('visible' => array('input[name="settings[enabled][lfm]"]' => array('checked' => TRUE))),
        ),
        'phone' => array(
          '#type' => 'checkbox',
          '#title' => t('Phone'),
          '#default_value' => $settings['required']['phone'] ?? TRUE,
          '#states' => array('visible' => array('input[name="settings[enabled][phone]"]' => array('checked' => TRUE))),
        ),
        'mail' => array(
          '#type' => 'checkbox',
          '#title' => t('E-mail'),
          '#default_value' => $settings['required']['mail'] ?? FALSE,
          '#states' => array('visible' => array('input[name="settings[enabled][mail]"]' => array('checked' => TRUE))),
        ),
      ),
    );
  }
}


/**
 * Implements hook_extra_field_widget_settings_summary()
 * @see addons.module -->> addons_form_field_ui_field_overview_form_alter()
 */
function order_extra_field_widget_settings_summary($entity_type, $bundle, $field_name, $settings) {
  if ($entity_type === 'node' && $bundle === 'order' && $field_name === 'order_information') {
    $enabled = !empty($settings['enabled']) && array_filter($settings['enabled']) ? $settings['enabled'] : array('lfm', 'phone', 'mail');
    $required = !empty($settings['required']) && array_filter($settings['required']) ? $settings['required'] : array('phone');

    $summary = array();
    $marker = theme('form_required_marker');

    if (!empty($enabled['lfm'])) {
      $summary[] = t('L.F.M.') . (!empty($required['lfm']) ? $marker : '');
    }
    if (!empty($enabled['phone'])) {
      $summary[] = t('Phone') . (!empty($required['phone']) ? $marker : '');
    }
    if (!empty($enabled['mail'])) {
      $summary[] = t('E-mail') . (!empty($required['mail']) ? $marker : '');
    }
    return '<strong>' . t('Fields') . ':</strong> ' . ($summary ? implode(', ', $summary) : t('none'));
  }
}


function order_is_complete($order_node) {
  if (!module_invoke('status', 'get_settings', 'node', 'order')) {
    // @todo delete is_paid condition?
    return !empty($order_node->nid) && !empty($order_node->order_status[ORDER_STATUS_DELIVERED]) && $order_node->is_paid;
  }
  else {
    return !empty($order_node->status_field['is_last_status']);
  }
}

/**
 * Returns TRUE if status <> first order status
 */
function _order_in_process($order_node) {
  if (!module_invoke('status', 'get_settings', 'node', 'order')) {
    return !empty($order_node->nid) && array_filter($order_node->order_status);
  }
  else {
    // @todo is_first_status
    $first_status_id = status_get_first_status_id('node', 'order');
    return $order_node->status_field['id'] != $first_status_id;
  }
}


/**
 * Returns TRUE if order was created $period days ago
 */
function _order_is_recent($order_node) {
  return ($period = shop_get_info('general', 'order_freeze'))
    ? ($order_node->created > REQUEST_TIME - $period * 24 * 60 * 60)
    : FALSE;
}


/**
 * Order is frozen if: paid OR in process OR recent
 */
function order_is_frozen($order_node) {
  return !empty($order_node->is_paid) || _order_in_process($order_node) || _order_is_recent($order_node);
}


/**
 * Implements hook_init()
 */
function order_init() {

}


/**
 * Implements hook_query_TAG_alter()
 */
function order_query_node_access_alter(QueryAlterableInterface $query) {
  // Deny view orders in search results
  if (($tables = $query->getTables()) && !empty($tables['i']['table']) && $tables['i']['table'] == 'search_index' && !empty($tables['n']['table']) && $tables['n']['table'] === 'node') {
    if (user_is_logged_in()) {
      if (!user_access('administer moneys')) {
        $query->condition(db_or()->condition('n.type', 'order', '<>')->condition('n.uid', $GLOBALS['user']->uid));
      }
    }
    else {
      $query->condition('n.type', 'order', '<>');
    }
  }
}


/**
 * Implements hook_entity_view_alter()
 */
function order_entity_view_alter(&$build, $type) {
  // IKW: Ќужно чтобы покупатели имели доступ к информации в статусных комментари€х  (https://itinity.ru/node/2191)
  // Revoke temporary granted perms (@see order_view())
  if ($type === 'node' && $build['#bundle'] === 'order') {
    if (!empty($build['#node']->_order_temporary_granted_perms)) {
      global $user;
      // modify user_access static storage
      $user_access = &drupal_static('user_access');
      foreach ($build['#node']->_order_temporary_granted_perms as $perm) {
        unset($user_access[$user->uid][$perm]);
      }
    }
  }
}


/**
 * Implements hook_view().
 */
function order_view($node, $view_mode) {

  // IKW: Ќужно чтобы покупатели имели доступ к информации в статусных комментари€х  (https://itinity.ru/node/2191)
  if (module_exists('changelog')) {
    global $user;
    // Temporary grant 'view entity changelog' permission for order owner before rendering and revoke it in order_entity_view_alter() hook.
    // @see also changelog_entity_view()
    if ($user->uid && ($node->uid == $user->uid || (!empty($node->customer) && $node->customer == $user->uid)) && !user_access('view entity changelog')) {
      // modify user_access static storage
      $user_access = &drupal_static('user_access');
      $node->_order_temporary_granted_perms['view entity changelog'] = $user_access[$user->uid]['view entity changelog'] = TRUE;
    }
  }

  if (node_is_page($node)) {
    if (_order_is_recent($node) && !$node->is_paid && !_order_in_process($node)) {
      $freeze_period = shop_get_info('general', 'order_freeze');
      $date = format_date($node->created + $freeze_period * 60 * 60 * 24);
      drupal_set_message(t('We guarantee items and delivery price preservation until %date', array('%date' => $date)));
    }
  }

  global $user;
  $title = _order_title($node);
  if ($view_mode === 'full') {
    if (arg(0) === 'node' && arg(1) == $node->nid) {
      if ($user->uid == $node->uid) {
        $bread = drupal_get_breadcrumb();
        $bread[] = theme('username', array('account' => $user));
        $bread[] = l(t('Orders'), 'user/' . $user->uid . '/shop/orders');
        drupal_set_breadcrumb($bread);
      }
    }
    if ($node->title === drupal_get_title()) {
      drupal_set_title($title);
    }
    $node->content['order_content']['shop_cart'] = array( // extra field
      '#type' => 'item',
      '#title' => t('Content of order'),
      theme('shop_cart', array(
        'mode' => 'max',
        'shop_cart' => shop_cart(NULL, NULL, $node),
      )),
    );
  }
  else {
    if ($view_mode == 'teaser') {
      $node->content['order_content']['shop_cart'] = array(
        '#type' => 'item',
        '#title' => t('Content of order') . ':',
        '#markup' => theme('shop_cart', array(
          'mode' => 'min',
          'shop_cart' => shop_cart(NULL, NULL, $node),
        )),
      );
    }
  }

  if (!empty($node->customer)) {
    $customer = user_load($node->customer);
  }
  else {
    $customer = drupal_anonymous_user();
//    $customer = isset($node->customer) ? drupal_anonymous_user() : ($node->uid ? user_load($node->uid) : drupal_anonymous_user());
  }

  $enabled = addons_extra_field_get_settings('node', 'order', 'form', NULL, 'order_information', 'enabled');
  $enabled = $enabled ?? drupal_map_assoc(array('lfm', 'phone', 'mail'));

  if ($lfm = !empty($node->recipient_fields['lfm']) ? trim($node->recipient_fields['lfm']) : ($customer->uid ? (!empty($customer->lfm) ? $customer->lfm : $customer->name) : NULL)) {
    $node->content['recipient']['recipient_lfm'] = array(
      '#type' => 'item',
      '#inline' => TRUE,
      '#title' => t('Recipient'),
      '#markup' => check_plain($lfm),
      '#access' => !empty($enabled['lfm']),
    );
  }
  if ($phone = !empty($node->recipient_fields['phone']) ? trim($node->recipient_fields['phone']) : ($customer->uid ? $customer->phone : NULL)) {
    $node->content['recipient']['recipient_phone'] = array(
      '#type' => 'item',
      '#inline' => TRUE,
      '#title' => t('Phone'),
      '#markup' => theme('phone', array('phone' => $phone)),
      '#access' => !empty($enabled['phone']),
    );
  }
  if ($mail = !empty($node->recipient_fields['mail']) ? trim($node->recipient_fields['mail']) : ($customer->uid ? $customer->mail : NULL)) {
    $node->content['recipient']['recipient_mail'] = array(
      '#type' => 'item',
      '#inline' => TRUE,
      '#title' => t('E-mail'),
      '#markup' => theme('email', array('email' => $mail,)),
      '#access' => !empty($enabled['mail']),
    );
  }
  if (!empty($node->content['recipient'])) {
    $node->content['recipient']['#type'] = 'item';
  }

  if ($customer) {
    $node->content['customer'] = array(
      '#type' => 'item',
      '#title' => t('Customer'),
      '#inline' => TRUE,
      '#markup' => theme('username', array('account' => $customer)),
    );
  }
  // payment_widget extra field:

  $node->content['payment_widget'] = array(
    '#type' => 'item',
    '#title' => t('Payment for order'),
    '#access' => !$node->is_paid,
  );

  $node->content['payment_status'] = array(
    '#type' => 'item',
    '#inlne' => TRUE,
    '#title' => t('Payment status'),
  );

  if (!$node->is_paid) {
    if ($holded = money_get_holded(NULL, 'order', $node->nid)) {
      $source = db_select('money_hold', 'mh')
        ->fields('mh', array('source', 'source_key'))
        ->condition('mh.operation', 'order')
        ->condition('mh.operation_key', $node->nid)->execute()->fetchAssoc();

      $source_info = money_sources_info($source['source'], $source['source_key']);

      $node->content['payment_status'] = array(
        '#type' => 'item',
        '#markup' => t('Holded for payment with !source: !sum', array('!source' => $source_info['overview']['title'], '!sum' => theme('price', array('price' => $holded)))),
      );
    }
    else {
      $node->content['payment_widget']['form'] = drupal_get_form('_order_payment_method_form', $node);
      if (!empty($node->payment_method)) {
        $node->content['payment_status']['#markup'] = t('Waits for payment');
      }
      else {
        $node->content['payment_status']['#access'] = FALSE;
      }
    }
  }
  else {
    if ($node->payment_method) {
      $sum = 0;
      if ($transactions = money_transaction_load_multiple(NULL, array('operation' => 'order', 'operation_key' => $node->nid))) {
        foreach ($transactions as $money_transaction) {
          $sum += $money_transaction->sum;
        }
        $node->content['payment_status']['#markup'] = l(t('Paid'), entity_uri('money_transaction', $money_transaction)['path'], array('attributes' => array('class' => array('ajax-popup',))));
      }
    }
    else {
      $node->content['payment_status']['#markup'] = t('Paid');
    }
  }

  if (!module_invoke('status', 'get_settings', 'node', 'order')) { // @see status.module

    $statuses = array();
    if (!$node->status) {
      $statuses[] = t('Not accepted');
    }
    if ($node->is_complete) {
      $statuses[] = t('Complete');
    }
    else {
      $statuses[] = t('Issued');
      foreach (_order_statuses() as $s => $t) {
        if (!empty($node->order_status[$s])) {
          $statuses[] = $t;
        }
      }
      if ($node->is_paid) {
        $statuses[] = t('Paid');
      }
    }
    $node->content['status_field'] = array(
      '#type' => 'item',
      '#inline' => TRUE,
      '#title' => t('Status'),
      'value' => array(
        '#markup' => drupal_ucfirst(drupal_strtolower(implode(', ', $statuses))) . '.',
      ),
      'change' => array(
        '#prefix' => ' ',
        '#access' => user_access('administer moneys'),
        '#type' => 'link',
        '#popup' => TRUE,
        '#title' => t('change'),
        '#href' => 'node/' . $node->nid . '/order_status',
        '#options' => array(
          'query' => drupal_get_destination(),
        ),
        '#attributes' => array(
          'class' => array('form-submit',),
        ),
      ),
    );
  }

  if (isset($node->delivery_method)) {
    if ($summary = shop_delivery_user_summary($node, $node->delivery_method, $node->delivery_params)) {
      $node->content['delivery'] = array(
        '#type' => 'item',
        '#title' => t('Delivery information'),
        'title' => array(
          '#markup' => shop_delivery_info($node, $node->delivery_method, 'title') . '. ',
        ),
        'summary' => $summary,
        //'#markup' => shop_delivery_info($node->delivery_method, 'title') . '. ' . $summary,
      );
    }
  }
  $node->title = $title;
  return $node;
}


function _order_payment_method_form($form, &$form_state, $node) {
  $form['#node'] = $node;

  $form['q'] = array(
    '#type' => 'hidden',
    '#value' => ($_GET['q'] !== 'system/ajax') ? $_GET['q'] : $form_state['values']['q'],
  );
  $_GET['q'] = $form['q']['#value'];

  $customer = shop_get_customer($node);
  $sum_to_paid = array_sum(shop_build_price('order', $node, $customer));

  $opts = array();
  $actions = array('#type' => 'actions',);
  $enabled_sources = _money_available_sources('order', $node->nid, $sum_to_paid, FALSE);
  $def_payment_method = $form_state['values']['payment_method'] ?? $node->payment_method ?? NULL;
  $def_payment_method = !empty($enabled_sources[$def_payment_method]) ? $def_payment_method : NULL;

  if (!$def_payment_method) {
    if (($default_source = shop_get_info('general', 'default_payment_method')) && !empty($enabled_sources[$default_source])) {
      $def_payment_method = $default_source;
    }
    if (count($enabled_sources) == 1) {
      $def_payment_method = key($enabled_sources);
    }
  }

  foreach ($enabled_sources as $source => $info) {
    if ($info['enabled'] && money_execute_access('order', $node->nid, $sum_to_paid, $info, FALSE, $m)) {
      $opts[$source] = $info['icon_url'] ? '<span class="payment-method-' . $source . '">' . theme_image(array('path' => $info['icon_url'], 'attributes' => array())) . '</span>' : '';
      $opts[$source] .= '<span class="payment-method-title">' . $info['title'] . '</span>';
      $opts[$source] .= ($info['description'] ? '<span class="payment-method-description">' . $info['description'] . '</span>' : '');
    }
  }

  if ($def_payment_method) {
    // Cash account injection
    if ($def_payment_method == 'user' && money_sources_info('user', NULL, 'settings', 'behavior') == 'hold') {
      if ($payment_widget = money_hold_widget('order', $node->nid, $sum_to_paid, $enabled_sources[$def_payment_method])) {
        $payment_widget['#attributes']['class'][] = 'default-submit';
        $actions['payment'] = $payment_widget;
      }
    }
    else {
      if ($payment_widget = money_payment_widget('order', $node->nid, $sum_to_paid, $enabled_sources[$def_payment_method])) {
        $payment_widget['#attributes']['class'][] = 'default-submit';
        $actions['payment'] = $payment_widget;
      }
    }
  }

  if ($opts) {
    $actions['confirm'] = array(
      '#type' => 'submit',
      '#value' => t('Confirm'),
      '#attributes' => array(
        'class' => array('js-hide',),
      ),
    );

    $wrapper_id = 'order-payment-method-form-ajax-wrapper-' . $node->nid;

    $form += array(
      '#prefix' => '',
      '#suffix' => '',
    );

    $form['#prefix'] = '<div id="' . $wrapper_id . '">' . $form['#prefix'];
    $form['#suffix'] .= '</div>';
    $form['payment_method'] = array(
      '#type' => 'radios',
      '#required' => TRUE,
      '#title' => t('Payment method'),
      '#title_display' => 'invisible',
      '#options' => $opts,
      '#ajax' => array(
        'wrapper' => $wrapper_id,
        'callback' => '_order_payment_method_form_ajax',
        'event' => 'click',
        'progress' => array(),
      ),
      '#default_value' => $def_payment_method,
    );
    $form['actions'] = $actions;
  }
  else {
    $form['#attributes']['class'][] = 'messages error';
    $form[]['#markup'] = t('Temporarily unavailable');
  }
  $form['#attached']['css'][] = drupal_get_path('module', 'order') . '/css/order.node.css';

  if (!$def_payment_method) {
    global $_SESSION;

    $session_backup = isset($_SESSION['messages']['status']) ? $_SESSION['messages']['status'] : NULL;
    $_SESSION['messages']['status'] = array(t("Please choose payment method"));

    $form['payment_method']['#prefix'] = theme('status_messages', array('display' => 'status'));

    if ($session_backup) {
      $_SESSION['messages']['status'] = $session_backup;
    }
  }

  $form['#submit'] = array('_order_payment_method_form_submit');

  return $form;
}

function _order_payment_method_form_ajax($form, &$form_state) {
  _order_payment_method_form_submit($form, $form_state);
  if (!empty($form['payment_method']['#options']) && !empty($form['payment_method']['#default_value'])) {
    $form['payment_method']['#prefix'] = theme('status_messages');
  }
  return $form;
}


function _order_payment_method_form_submit($form, &$form_state) {
  if (($node = node_load($form_state['build_info']['args'][0]->nid)) && !$node->is_paid) {
    if ($node->payment_method !== $form_state['values']['payment_method']) {
      $node->payment_method = $form_state['values']['payment_method'];
      node_save($node);
      // only for ajax:
      // bespolezno $form_state['build_info']['args'][0] = $node;
      // bespolezno $form_state['rebuild'] = TRUE;
      $msg[] = 'Thanks for purchase!';
      if ($node->payment_method === 'cash') {
        $msg[] = 'Please prepare moneys needed for purchase.';
      }
      elseif ($node->payment_method === 'invoice') {
        $msg[] = 'Download or print invoice and pay it.';
      }
      else {
        $msg[] = 'It remains only to pay for the order.';
      }
      drupal_set_message(implode(' ', array_map('t', $msg)));
    }
  }
}


/**
 * Helper function - format order node title
 */
function _order_title($node) {
  return empty($node->ya_market_id) ? t('Order #@number', array('@number' => $node->order_num)) : t('Order #@number (order from Yandex.Market, ID = @ya_market_id)', array('@number' => $node->order_num, '@ya_market_id' => $node->ya_market_id));
}


/**
 * Helper function - bitwise conversion order_status database value into array of statuses
 */
function _order_extract_status($node) {
  $order_status = isset($node->order_status) ? $node->order_status : ORDER_STATUS_DELIVERY_ISSUED;
  $node->order_status = array(ORDER_STATUS_DELIVERY_ISSUED => ORDER_STATUS_DELIVERY_ISSUED);
  foreach (_order_statuses() as $status => $title) {
    if ($order_status & $status) {
      $node->order_status[$status] = $status;
    }
  }
}


/**
 * Implements hook_validate().
 */
function order_validate($node, $form, &$form_state) {
  $checkout_clicked = $form_state['triggering_element']['#value'] === $form['actions']['submit']['#value'];
  $node->shop_id = $node->shop_cart['shop_id'];
  if ($checkout_clicked && empty($node->nid) && shop_cart(NULL, NULL, $node)->is_empty(FALSE)) {
    form_error($form['order_content']['shop_cart'], t('Cart is empty, You can not checkout order without goods.'));
  }

  $node->recipient_fields['mail'] = trim($node->recipient_fields['mail']);
  $node->recipient_fields['phone'] = trim($node->recipient_fields['phone']);
  $node->recipient_fields['lfm'] = trim($node->recipient_fields['lfm']);

  if (empty($form_state['values']['shop_cart']['order_discount']['order_discount'])) {
    $form_state['values']['shop_cart']['order_discount']['order_discount'] = 0;
    $form_state['values']['shop_cart']['order_discount']['order_discount_text'] = '';
  }

  $node->order_discount = $form_state['values']['shop_cart']['order_discount']['order_discount'];
  $node->order_discount_text = trim($form_state['values']['shop_cart']['order_discount']['order_discount_text']);

  /*
  if (!empty($node->customer) && ($acc = user_load($node->customer))) {
    if ($node->recipient_fields['lfm'] && ($username = format_username($acc))) {
      $lfm = preg_replace('/\s+/u', ' ', trim(drupal_strtolower($node->recipient_fields['lfm'])));
      $username = preg_replace('/\s+/u', ' ', trim(drupal_strtolower($username)));
      if ($lfm === $username) {
        unset($form_state['values']['recipient_fields']['lfm'], $node->recipient_fields['lfm']);
      }
    }
    if ($node->recipient_fields['phone'] && !empty($acc->phone)) {
      if (addons_format_phone($node->recipient_fields['phone']) === addons_format_phone($acc->phone)) {
        unset($form_state['values']['recipient_fields']['phone'], $node->recipient_fields['phone']);
      }
    }
    if ($node->recipient_fields['mail']) {
      if (drupal_strtolower($node->recipient_fields['mail']) === trim(drupal_strtolower($acc->mail))) {
        unset($form_state['values']['recipient_fields']['mail'], $node->recipient_fields['mail']);
      }
    }
  }
  */

  global $user;
  if (!empty($node->recipient_fields['mail']) && user_load_by_mail($node->recipient_fields['mail'])) {
    if (!$user->uid) {
      // IKW: no errors, display only warning message
      drupal_set_message(
        t('This e-mail (@email) already used in user account on a site.', array(
          '@email' => $node->recipient_fields['mail'],
        )) .
        ' ' .
        t('Perhaps You already have an account here before. Please <a href="@url">log-in</a> on a site.', array(
          '@url' => url('user', array('query' => array('destination' => $_GET['q']))),
        )), 'warning');
    }
    // Do not allow registerd users attach orders to another registered email
    elseif ($checkout_clicked && drupal_strtolower($node->recipient_fields['mail']) !== drupal_strtolower($user->mail) && !user_access('administer moneys')) {
      form_error($form['order_information']['recipient_fields']['mail'],
        t('This e-mail (@email) already used in another account on a site.', array(
          '@email' => $node->recipient_fields['mail'],
        )) .
        ' ' .
        t('If You have other account registered to @email, please log-in using this e-mail.', array(
          '@email' => $node->recipient_fields['mail'],
        )));
    }
  }

  if ((empty($node->order_discount) || empty($node->order_discount_text)) && !(empty($node->order_discount) && empty($node->order_discount_text))) {
    $empty_field = empty($node->order_discount)
      ? $form['order_content']['shop_cart']['order_discount']['order_discount']
      : $form['order_content']['shop_cart']['order_discount']['order_discount_text'];

    form_error($empty_field, t('The field %field is required.', array(
      '%field' => $empty_field['#title'],
    )));
  }
}


/**
 * Implements hook_insert().
 */
function order_insert($node) {
  $node->order_status = !isset($node->order_status) ? array() : $node->order_status;

  if (!is_array($node->order_status)) {
    _order_extract_status($node);
  }

  //TODO: Currently Drupal does not allow to modify the node itself
  //replace when module_invoke_all allow references in hook functions
  //module_invoke_all('order_status_change', $node->order_status, $node);

  $node->order_status = array_sum($node->order_status);

  unset($node->order_num);

  $clone = clone $node;
  unset($clone->nid);
  $shop_cart = shop_cart(NULL, NULL, $clone); // load shop_cart by order node but from {shop_cart_items} (NOT from {shop_cart_items_ordered})
  $shop_cart->order($node);


  $node->delivery_price = shop_build_price('order', $node, NULL, 'delivery');
  $node->delivery_price = !$node->delivery_price && in_array($node->delivery_price, array('', FALSE), TRUE) ? NULL : $node->delivery_price;  // Crutch for PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect decimal value: '' for column 'delivery_price'
  $node->delivery_params = !empty($node->delivery_params) ? serialize($node->delivery_params) : NULL;
  $node->tracking_id = anonymous_tracker_track_user(NULL, 'id');
  drupal_write_record('shop_orders', $node);
  $node->delivery_params = $node->delivery_params ? unserialize($node->delivery_params) : NULL;
  _order_extract_status($node);
  $node->title = _order_title($node);
  db_query('UPDATE {node} SET title = :title WHERE nid = :nid', array(':nid' => $node->nid, ':title' => $node->title,));
  db_query('UPDATE {node_revision} SET title = :title WHERE nid = :nid', array(':nid' => $node->nid, ':title' => $node->title,));

  $node->is_complete = order_is_complete($node);

  _order_track_balances($node);

  if (!empty($node->is_new) && !$shop_cart->is_empty()) {
    if ($node->uid && ($acc = user_load($node->uid))) {
      $mail = $acc->mail;
      $lang = user_preferred_language($acc);
      $account = $acc;
    }
    elseif (!$node->uid && empty($node->customer)) {
      $mail = !empty($node->recipient_fields['mail']) ? $node->recipient_fields['mail'] : variable_get('site_mail', ini_get('sendmail_from'));
      $lang = $GLOBALS['language'];
      $account = $GLOBALS['user'];
    }
    //if(isset($mail) && isset($lang) && isset($account)) {
    $params = array(
      'order' => $node,
      'shop_cart' => $shop_cart,
    );
    if (isset($account)) {
      $params['account'] = $account;
    }

    drupal_mail('order', 'order_inserted', isset($mail) ? $mail : '', isset($lang) ? $lang : language_default(), $params);

    if ($node->order_discount) {
      order_changelog($node);
    }
  }
}


/**
 * Implements hook_update().
 */
function order_update($node) {
  $node->payment_method = isset($node->payment_method) ? $node->payment_method : NULL;
  if (!is_array($node->order_status)) {
    _order_extract_status($node);
  }

  $previous_state = $node->original;
  unset($previous_state->previous_state);
  $node->previous_state = serialize($previous_state);
  $node->order_status = array_sum($node->order_status);

  $node->delivery_price = shop_build_price('order', $node, NULL, 'delivery');
  $node->delivery_price = !$node->delivery_price && in_array($node->delivery_price, array('', FALSE), TRUE) ? NULL : $node->delivery_price; // Crutch for PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect decimal value: '' for column 'delivery_price'
  $node->delivery_params = $node->delivery_params ? serialize($node->delivery_params) : NULL;
  drupal_write_record('shop_orders', $node, array('order_num'));
  $node->delivery_params = $node->delivery_params ? unserialize($node->delivery_params) : NULL;
  _order_extract_status($node);
  $node->previous_state = $previous_state;
  //spike for node title in status message
  $node->title = t('#@number', array('@number' => $node->order_num));


  $node->is_complete = order_is_complete($node);

  _order_track_balances($node);

  $order_discount = $node->order_discount ?? NULL;
  $order_discount_text = $node->order_discount_text ?? NULL;
  $original_order_discount = $node->original->order_discount ?? NULL;
  $original_order_discount_text = $node->original->order_discount_text ?? NULL;

  if ($order_discount != $original_order_discount || $order_discount_text != $original_order_discount_text) {
    order_changelog($node);
  }
}


function order_changelog($order) {
  global $user;

  changelog_add(
    $order,
    'node',
    'order',
    'User %user set order discount to %od, comment: %c',
    array(
      '%user' => format_username($user),
      '%od' => html_entity_decode(strip_tags(theme('price', array('price' => $order->order_discount)))),
      '%c' => $order->order_discount_text)
  );
}


/**
 * Reindex goods qty's in store by current updated/inserted/deleted order
 * @param $increment - boolean flag for increase or decrease qty
 */
function _order_update_products_qty($order, $increment) {
  $shop_cart = shop_cart(NULL, NULL, $order);
  foreach ($shop_cart->items as $item) {
    if (function_exists($save_callback = $item->entity_type . '_save') && ($entities = entity_load($item->entity_type, array($item->entity_id))) && ($entity = reset($entities)) && isset($entity->qty)) { // qty is NULL - skip operation because qty already is infinity
      if (isset($entity->status)) { // entity has standard status field?
        $old_qty = $entity->qty;
        $new_qty = $increment ? $old_qty + $item->qty : $old_qty - $item->qty;
        $new_qty = max($new_qty, 0); // prevent negative qty
        if ($old_qty != $new_qty) {
          $entity->qty = $new_qty;
          $save_callback($entity); // call node_save(), user_save(), etc
          if (arg(0) . '/' . arg(1) === 'node/' . $order->nid) {
            // Display messages only if current order concides with current URL (non-programmatic operation)
            $label = entity_label($item->entity_type, $entity);
            if ($increment) {
              drupal_set_message(format_plural($new_qty - $old_qty, 'Product @title has been returned to store', '@count of products hes been returns to store', array('@title' => $label)));
            }
            else {
              drupal_set_message(format_plural($old_qty - $new_qty, 'Product @title has been write-off from store', '@count of products hes been write-off from store', array('@title' => $label)));
            }
          }
        }
      }
    }
  }
}


/**
 * Implements hook_delete().
 */
function order_delete($node) {
  $node->order_delete = TRUE; // flag used in _order_track_balances()
  _order_track_balances($node);

  db_query('DELETE FROM {shop_cart_items_ordered} WHERE oid = :oid', array(':oid' => $node->nid));
  db_query('DELETE FROM {shop_orders} WHERE nid = :nid', array(':nid' => $node->nid));
}


/**
 * Implements hook_node_update()
 * SPIKE
 * send email for user
 */
function order_node_update($node) {
  if ($node->type === 'order' && $node->created != $node->changed && !module_invoke('status', 'get_settings', 'node', 'order')) { // @see status.module
    if (array_sum($node->order_status) != array_sum($node->original->order_status) || $node->status != $node->original->status) {

      $account = user_load($node->uid);
      $to = array(format_username($account) . ' <' . $account->mail . '>');

      $language = user_preferred_language($account);
      $options = array(
        'order' => $node,
      );
      drupal_mail('order', 'order_status_changed', implode(',', $to), $language, $options);
    }
  }
}


/**
 * Implements hook_drupal_goto_alter()
 */
function order_drupal_goto_alter(&$path, &$options, &$http_response_code) {
  if ($_GET['q'] === 'user/password' && arg(0, $path) . '/' . arg(1, $path) . '/' . arg(3, $path) === 'shop/cart/checkout' && arg(4, $path) && !empty($_GET['destination']) && $_GET['destination'] === $path) {
    if (arg(4, $path) === drupal_hmac_base64('shop-cart-checkout', shop_cart(arg(2, $path))->currentKey() . drupal_get_private_key() . drupal_get_hash_salt())) {
      $path = $_GET['q'];
      $options['query']['destination'] = $_GET['destination'];
    }
  }
}

//////// Money API


/**
 * Imlements hook_money_operations_info()
 */
function order_money_operations_info($operation = NULL, $operation_key = NULL) {
  $result = array(
    'order' => array(
      'title' => t('Payment for order'),
    ),
  );

  if ($operation === 'order' && $operation_key) {
    if (($node = node_load($operation_key)) && ($node->type === 'order')) {
      $customer = shop_get_customer($node);
      $order_price = array_sum(shop_build_price('order', $node, $customer));

      $title = t('Payment for order #@num', array('@num' => $node->order_num));
      $result['order']['title'] = $title;
      $result['order']['price'] = $order_price;

      $result['order']['overview']['title'] = node_access('view', $node) ? l($title, "node/{$node->nid}") : $title;
    }
  }

  return $result;
}


/**
 * Implements hook_money_operation_get_recipient()
 */
function order_money_operation_get_recipient($operation, $operation_key) {
  if ($operation === 'order') {
    return 'site';
  }
}


/**
 * Implements hook_money_operation_get_customer()
 * @todo replace shop_get_customer() with money_operation_get_customer() everywhere!
 */
function order_money_operation_get_customer($operation, $operation_key) {
  if (($operation == 'order') && ($order = node_load($operation_key))) {
    $customer = shop_get_customer($order);
    return $customer->uid;
  }
}


/**
 * Imlements hook_money_execute_access()
 */
function order_money_execute_access($operation, $operation_key, $sum = NULL, $source_info = NULL, $before_insert = FALSE, &$error_messages = NULL) {

  if ($operation === 'order') {
    if (!$operation_key) {
      return TRUE;
    }
    elseif (!($node = node_load($operation_key))) {
      $error_messages[] = t('Order not found');
      return FALSE;
    }
    elseif ($node->type !== 'order') {
      $error_messages[] = t('Only order node type');
      return FALSE;
    }
    elseif (!empty($node->is_paid)) {
      $error_messages[] = t('Order already paid');
      return FALSE;
    }
    //elseif (!module_exists('cash_account') && !empty($node->payment_method) && $source_info && $source_info['source'] !== $node->payment_method) {
    //  $error_messages[] = t('Payment method not allowed for this order');
    //  return FALSE;
    //}
    elseif (!array_sum(shop_build_price('order', $node, $node->uid))) {//empty($node->order_required_sum)) {
      $error_messages[] = t('Order is not requires money');
      return FALSE;
    }
    elseif (!$node->status && !user_access('administer moneys')) {
      $error_messages[] = t('Order is not published');
      return FALSE;
    }
    elseif ($sum . '' !== array_sum(shop_build_price('order', $node, $node->uid)) . '') {//$node->order_required_sum . '') { // Use $var . '' !!! (bug of php, problem with double != double placed in array)
      $error_messages[] = t('Sum not equals to @sum', array('@sum' => array_sum(shop_build_price('order', $node))));
      return FALSE;
    }
    elseif ((!user_is_logged_in() && $node->uid) || (user_is_logged_in() && !node_access('view', $node))) {
      $error_messages[] = t('Only for order owners or administrators');
      return FALSE;
    }
    elseif ($source_info && !module_exists('cash_account')) {
      if (empty($node->delivery_method)) {
        // Check what current money source is allowed in all enabled delivery methods
        foreach (shop_delivery_info($node) as $m => $info) {
          if ($info['enabled']) {
            $payment_allow = shop_delivery_info($node, $m, 'payment_allow');
            $payment_allow = $payment_allow ? array_filter($payment_allow) : NULL;
            if ($payment_allow && !in_array($source_info['source'], $payment_allow, TRUE)) {
              $error_messages[] = t('Delivery method must be specified first.');
              return FALSE;
            }
          }
        }
      }
      elseif (($payment_allow = shop_delivery_info($node, $node->delivery_method, 'payment_allow')) && ($payment_allow = array_filter($payment_allow)) && !in_array($source_info['source'], array_filter($payment_allow), TRUE)) {
        $error_messages[] = t('Payment method is denied for selected delivery method.');
        return FALSE;
      }
    }
    return TRUE;
  }
}


/**
 * Implements hook_money_transaction_prepare()
 */
function order_money_transaction_prepare($money_transaction) {
  if ($money_transaction->operation === 'order') {
    if ($order = node_load($money_transaction->operation_key)) {
      foreach (shop_cart(NULL, NULL, $order)->items as $item) {
        $money_transaction->items[] = array(
          'title' => $item->title,
          'qty' => $item->qty,
          'qty_type' => $item->qty_type,
          'price' => array_sum(shop_build_price('shop_cart_item', $item)),
          'real_price' => $item->si_price,
        );
      }
      $summary = shop_build_price('order', $order);
      $money_transaction->order_summary = $summary;
      if (!empty($summary['delivery'])) {
        $money_transaction->items[] = array(
          'title' => t('Delivery') . ' (' . shop_delivery_info($order, $order->delivery_method, 'title') . ')',
          'qty' => 1,
          'price' => $summary['delivery'],
        );
      }
      // Fiscal information
      // Needed for KKT (fiscal module) @see fiscal_receipt_by_money_transaction()
      $money_transaction->fiscal_info = array(
        'positions' => $money_transaction->items,
        'payer_phone' => $order->recipient_fields['phone'],
        'payer_mail' => $order->recipient_fields['mail'],
      );      
    }
  }
}

/**
 * Implements hook_money_transaction_presave()
 */
function order_money_transaction_presave($money_transaction) {
  if ($money_transaction->operation === 'order') {
    if ($order = node_load($money_transaction->operation_key)) {
      $money_transaction->uri = entity_uri('node', $order)['path'];
    }
  }
}


/**
 * Implements hook_money_transaction_insert()
 */
function order_money_transaction_insert($money_transaction) {
  if ($money_transaction->operation === 'order') {
    if (($order = node_load($money_transaction->operation_key)) && $order->type === 'order' && !$order->is_paid) {
      $order->is_paid = TRUE;
      $order->payment_method = $money_transaction->source;
      $order->payment_timestamp = $money_transaction->timestamp;
      node_save($order);
      _order_trigger($order, 'order_paid');
      if (module_exists('changelog')) {
        changelog_add(
          $order,
          'node',
          'order',
          'Order was paid',
          array(),
          'payment',
          NULL,
          $money_transaction->uid
        );
      }
      drupal_mail('order', 'payment_accepted', isset($mail) ? $mail : '', isset($lang) ? $lang : language_default(), array(
        'order' => $order,
        'shop_cart' => shop_cart(NULL, NULL, $order),
      ));
    }
  }
}


/**
 * Implements hook_form_FORM_ID_alter()
 */
function order_form_money_payment_form_alter(&$form, &$form_state, $form_id) {
  if ($form['operation']['#value'] === 'order' && ($nid = $form['operation_key']['#value'])) {
    // Set preferred payment method for orders that already have payment_method property.
    if (!empty($form['source']['#options']) && !$form['source']['#default_value']) {
      if (($node = node_load($nid)) && $node->payment_method && isset($form['source']['#options'][$node->payment_method])) {
        $form['source']['#default_value'] = $node->payment_method;
        // Move default option to top
        $form['source']['#options'] = array($node->payment_method => $form['source']['#options'][$node->payment_method]) + $form['source']['#options'];
      }
    }
  }
}


/**
 * Implements hook_user_delete()
 */
function order_user_delete($account) {
  // IKW: An customer field can be guest (0) or NULL if not specified, or any user uid
  // Implementation: set guest because uid of customer was specified
  db_query('UPDATE {shop_orders} SET customer = 0 WHERE customer = :uid', array(':uid' => $account->uid,));
}


/**
 * Implements hook_microwidgets_info().
 * IKW: 90% пользователей будет только 1 активный заказ.
 * если заказов > 1, то показывать в микровиджете ссылку на список заказов
 */
function order_microwidgets_info() {
  global $user;

  if (!user_is_logged_in()) {
    return;
  }

  $nids = db_select('shop_orders', 'so')
    ->fields('so', array('nid'))
    ->condition('so.customer', $user->uid)
    ->orderBy('so.order_num', 'DESC')
    ->execute()->fetchCol();


  $node = array();

  if ($nids) {
    foreach (node_load_multiple($nids) as $nid => $order) {
      if ($order->status && !$order->is_complete) {
        $node[] = $order;
      }
    }
  }

  $content = array();

  if (count($node) > 1) {
    $content['link'] = array(
      '#type' => 'link',
      '#title' => format_plural(count($node), "You have 1 order", "You have @count orders"),
      '#href' => 'user/' . $user->uid . '/shop/orders',
    );
  }
  elseif (count($node) == 1) {
    $node = reset($node);

    $content['order_link'] = array(
      '#type' => 'link',
      '#title' => module_exists('pictogram') ? theme('pictogram', array('icon' => 'gift')) . ' <span>' . t('#') . $node->order_num . '</span>' : $node->title,
      '#href' => 'node/' . $node->nid,
      '#options' => array(
        'html' => TRUE,
      ),
    );

    if (module_invoke('status', 'get_settings', 'node', 'order')) {
      $status_view = status_view_status_field($node);
      $content['status'] = $status_view['status_field']['content']['status_name'];
    }

    if (!$node->is_paid && ($node->payment_method != 'cash')) {
      $widget = money_payment_widget('order', $node->nid, array_sum(shop_build_price('order', $node, $node->uid)), $node->payment_method);
      $widget['#title'] = t('Pay');
      $content['action'] = $widget;
    }
  }

  $info = array(
    'title' => t("Order's microwidget"),
    'content' => $content ?? array(),
  );

  return $info;
}


/**
 * Implements hook_theme_registry_alter().
 */
function order_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['invoice'])) {
    $theme_registry['invoice']['preprocess functions'][] = 'order_preprocess_invoice';
  }
}

function order_preprocess_invoice(&$variables) {
  $mt = $variables['money_transaction'];

  if ($mt->operation == 'order' && !empty($mt->operation_key)) {
    $order = node_load($mt->operation_key);
    $variables['purchase']['number'] = $order->order_num;
  }
}


function order_form_money_config_form_alter(&$form, &$form_state, $form_id) {
  $form['order_freeze'] = array(
    '#type' => 'digit',
    '#title' => t('Order freeze period'),
    '#description' => t('The order item prices and delivery terms will be fixed during this period, even if changed'),
    '#field_suffix' => t('days'),
    '#size' => 4,
    '#min' => 0,
    '#step' => 1,
    '#buttons' => TRUE,
    '#default_value' => shop_get_info('general', 'order_freeze'),
  );

  $form['#submit'][] = 'order_form_money_config_form_alter_submit';
}

function order_form_money_config_form_alter_submit(&$form, &$form_state) {
  if (isset($form_state['values']['order_freeze'])) {
    $shop_info = shop_get_info();
    $shop_info['general']['order_freeze'] = $form_state['values']['order_freeze'];
    shop_update_info($shop_info);
  }
}


/**
 * Implements hook_status_change_node_status().
 */
function order_status_change_node_status($node) {
  if ($node->type == 'order') {
    /**
     * WORKAROUND
     * because status changing does not updates node object
     */
    $node = node_load($node->nid, NULL, TRUE);
    $node->original = new stdClass();
    $node->original->is_complete = !empty($node->status_field['original']['is_last_status']); // @see order_is_complete();
    _order_track_balances($node);


    // Proceed holded order operation if exists
    if (!empty($node->status_field['is_last_status']) && !$node->is_paid) {
      if ($holded = money_get_holded(NULL, 'order', $node->nid)) {
        $data = db_select('money_hold', 'mh')
          ->fields('mh', array('source', 'source_key', 'sum'))
          ->condition('mh.operation', 'order')
          ->condition('mh.operation_key', $node->nid)->execute()->fetchAssoc();

        $source_info = money_sources_info($data['source'], $data['source_key']);

        money_transaction_begin();
        $money_transaction = money_new_transaction(array(
          'operation' => 'order',
          'operation_key' => $node->nid,
          'sum' => $data['sum'],
          'source' => $source_info['source'],
          'source_key' => $source_info['key'],
        ));
        money_transaction_save($money_transaction);
        money_transaction_finish();
      }
    }


    if (!$node->frozen) {
      $node->delivery_price = shop_build_price('order', $node, NULL, 'delivery');
      $node->delivery_price = !$node->delivery_price && in_array($node->delivery_price, array('', FALSE), TRUE) ? NULL : $node->delivery_price; // Crutch for PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect decimal value: '' for column 'delivery_price'
      db_query('UPDATE {shop_orders} SET delivery_price = :p WHERE nid = :n', array(
        ':p' => $node->delivery_price,
        ':n' => $node->nid,
      ));
    }

  }
}


function _order_track_balances($order) {
  if (shop_get_info('balances', 'settings', 'track')) {
    $product_debit_condition = shop_get_info('balances', 'settings', 'product_debit_condition');

    $prev_state = FALSE;
    $curr_state = FALSE;
    $del_flag = !empty($order->order_delete); // Custom context indicates that order deletion is called  @see order_delete()

    if ($product_debit_condition === 'created') {
      $curr_state = !empty($order->is_new);
      $prev_state = !$curr_state;
    }
    elseif ($product_debit_condition === 'completed') {
      $prev_state = !empty($order->original->is_complete);
      $curr_state = !empty($order->is_complete);
    }
    elseif ($product_debit_condition === 'paid') {
      $prev_state = !empty($order->original->is_paid);
      $curr_state = !empty($order->is_paid);
    }

    if ($curr_state && $del_flag) {
      _order_update_products_qty($order, TRUE);
    }
    elseif ($curr_state != $prev_state) {
      _order_update_products_qty($order, !$curr_state);
    }
  }
}

/**
 * Implements hook_trigger_info().
 */
function order_trigger_info() {
  return array(
    'node' => array(
      'order_paid' => array(
        'label' => t('Order is paid'),
      ),
    ),
  );
}


function _order_trigger($entity, $hook, $a3 = NULL, $a4 = NULL) {
  if (!module_exists('trigger')) {
    return; // do nothing
  }

  // Keep objects for reuse so that changes actions make to objects can persist.
  static $objects;
  // Prevent recursion by tracking which operations have already been called.
  static $recursion;

  $aids = trigger_get_assigned_actions($hook);

  if (!$aids) {
    return;
  }

  if (isset($recursion[$hook])) {
    return;
  }

  $recursion[$hook] = TRUE;

  $context = array(
    'group' => 'node',
    'hook' => $hook,
    'nid' => $entity->nid,
    'order' => $entity->order_num,
  );

  // We need to get the expected object if the action's type is not 'money_transaction'.
  // We keep the object in $objects so we can reuse it if we have multiple actions
  // that make changes to an object.
  foreach ($aids as $aid => $info) {
//    $type = $info['type'];
//    if ($type != 'node') {
//      if (!isset($objects[$type])) {
//        $objects[$type] = _order_trigger_normalize_context($type, $money_transaction);
//      }
//      // Since we know about the money_transaction, we pass that info along to the action.
//      $context['money_transaction'] = $money_transaction;
//      $result = actions_do($aid, $objects[$type], $context, $a3, $a4);
//    }
//    else {
      actions_do($aid, $entity, $context, $a3, $a4);
//    }
  }

  unset($recursion[$hook]);
}


/**
 * @todo
 */
function _order_trigger_normalize_context($type, $entity) {

}


/**
 * Implements hook_action_info().
 */
function order_action_info() {
  return array(
    'order_unhold_money' => array(
      'type' => 'node',
      'label' => t('Unhold money'),
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}


/**
 * Unhold order money
 */
function order_unhold_money($node, $context = array()) {
  if ($node->type == 'order') {
    money_unhold('order', $node->nid);
  }
}